# In .travis.yml
gemfile:
  - gemfiles/rails_4.2.11.gemfile
  - gemfiles/rails_5.0.7.1.gemfile
  - gemfiles/rails_5.1.6.1.gemfile
  - gemfiles/rails_5.2.1.1.gemfile

language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5

install:
  - "bundle install"

script:
  - "bundle exec rspec"
